repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.3
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_validate
        args:
          - --args=-no-color
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_tflint
        args:
          - --args=--call-module-type=all
          - --args=--enable-rule=terraform_documented_variables

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.7.0
    hooks:
      - id: ansible-lint
        files: ^(?!\.).*\.(yaml|yml)$
        verbose: true
